const products = [
  {
    id: 0,
    title: "Model S",
    name: "Model S",
    description: "Order Online for Touchless Delivery",
    image: "model-s.jpg",
    range: "390",
    time: "1.99",
    topSpeed: "200",
    peakPower: "1,020",
    btn1: "custom order",
    btn2: "existing inventory",
    ref: "model_s",
  },
  {
    id: 3,
    title: "Model Y",
    name: "Model Y",
    description: "Order Online for Touchless Delivery",
    image: "model-y.jpg",
    range: "410",
    time: "2.05",
    topSpeed: "190",
    peakPower: "1,040",
    btn1: "custom order",
    btn2: "existing inventory",
    ref: "model_y",
  },
  {
    id: 1,
    title: "Model 3",
    name: "Model 3",
    description: "Order Online for Touchless Delivery",
    image: "model-3.jpg",
    range: "400",
    time: "2.99",
    topSpeed: "180",
    peakPower: "900",
    btn1: "custom order",
    btn2: "existing inventory",
    ref: "model_3",
  },
  {
    id: 2,
    title: "Model X",
    name: "Model X",
    description: "Order Online for Touchless Delivery",
    image: "model-x.jpg",
    range: "350",
    time: "1.55",
    topSpeed: "150",
    peakPower: "1,130",
    btn1: "custom order",
    btn2: "existing inventory",
    ref: "model_x",
  },
  {
    id: 4,
    title: "Lowest Cost Solar Panels in America",
    name: "solar panel",
    image: "solar-panel.jpg",
    description: "Money-back gurantee",
    btn1: "Order Now",
    btn2: "Learn More",
    ref: "solar_panel",
  },
  {
    id: 5,
    title: "Solar for New Roofs",
    name: "solar roof",
    image: "solar-roof.jpg",
    description: "Solar Roof Cost Less Than a New Roof",
    btn1: "Order Now",
    btn2: "Learn More",
    ref: "solar_roof",
  },
  {
    id: 6,
    title: "accessories",
    name: "accessories",
    btn1: "shop now",
    image: "accessories.jpg",
    ref: "accessories",
  },
];

export default products;
